### PR TITLE
fix issue 4 (for chrome 17)

### PR DESCRIPTION
**Pull request by Longer**
Hi. I fixed u issue 4 (and 8). But it maybe broke in previous version of chrome (need test it).

### CODE REVIEW

**Comment by aceat64** [comment]
Thank you. I'm testing this now, will merge if everything looks good.

**Comment by disfated** [comment]
why need bookmarks permission now?

**Comment by Longer** [comment]
It's cause permission error  as in https://github.com/aceat64/MailCheckerMinus/issues/8 but now if i remove it - nothing changing, very strange.

**Comment by Longer** [comment]
I'm not yet update official version, but him write:
Error in event handler for 'undefined': TypeError: Cannot read property 'length' of undefined
    at setupPageActionEvents (extensions/schema_generated_bindings.js:420:36)
    at extensions/schema_generated_bindings.js:1063:5
    at [object Object].dispatch (extensions/event.js:183:28)
    at Object.<anonymous> (extensions/event.js:238:25)

extensions/schema_generated_bindings.js:184Uncaught Error: You do not have permission to use 'browserAction.setBadgeBackgroundColor'. Be sure to declare in your manifest what permissions you need.

**Pull request merged**
